### ISSUE TITLE
Install issue - Lighthttpd

### ISSUE THREAD

**Issue by elRadix** [Optware/Optware-ng#106]
Is this issue with the download server ?

```
[admin@router /]$ ipkg install lighttpd
Installing lighttpd (1.4.32-1) to /opt/...
Nothing to be done
An error ocurred, return value: 28.
Collected errors:
Only have 0 available blocks on filesystem /, pkg lighttpd needs 1452
```

**Comment by alllexx88** [comment]
You have armv7 router, right? I've recently added Installed-Size field to the ipks, and switched to opkg, patched to use ipkg paths. It's also patched to check for free space in `/opt`, instead of `/`. To fix your issue, you just have to upgrade ipkg: to do that, run the bootstrap script again -- it will not affect your installed packages. I'm planning to add an announcement to the README when all feeds are rebuilt (armv7 is ready -- hence your problem)
