### ISSUE TITLE
WDC MyBook World II NAS Support

### ISSUE THREAD

**Issue by hondzik** [Optware/Optware-ng#107]
Hello,
I found this project when I was looking for a new version of MySql for my WDC MyBook World II (WhiteLight). I was using the original optware, but the packages are getting very old.

I tried both arm5 versions of ipkg package manager, but I always got "Illegal instruction" error when I tried to run it. According to uname there is Linux 2.6.24.4 installed on this NAS:
Linux MyBookWorld 2.6.24.4 #1 Thu Apr 1 16:43:58 CST 2010 armv5tejl unknown

Is it possible for you to support this device?

Thanks,
Jan

**Comment by alllexx88** [comment]
Hi,
`buildroot-armv5eabi-ng` feed uses 2.6.36.4 kernel headers, which are probably too new for WD MyBook World Edition II. `buildroot-armv5eabi-ng-legacy` feed is currently broken: I tried to build with 2.6.12 kernel headers, which turned out to be a bad idea. I'm now rebuilding it with 2.6.22 kernel headers, which should hopefully work for MBWE II

**Comment by hondzik** [comment]
Hi,
thank you for your support. Please let me know when the buildroot-armv5eabi-ng-legacy feed is ready.

Thanks,
Jan

**Comment by alllexx88** [comment]
@hondzik built and uploaded. If the feed works for you in general (hope it does), make sure you have enough swap memory, since mysql 5.7.9 is pretty memory-demanding. 2GB is a good bet

**Comment by hondzik** [comment]
Thank you very much, I will try it on the evening...

**Comment by alllexx88** [comment]
@hondzik have you managed to try it? I'm pretty curious myself whether it works or not, since WD MBWE 1 was the reason I originally got into the world of Linux :-) MBWE I stock firmware runs an OABI kernel, and even though MyLenny firmware I shared back in the old days is EABI, it's still just 2.6.17.14 linux, which is too outdated to support. But MBWE II runs 2.6.24.4 EABI kernel, which should hopefully work fine with `buildroot-armv5eabi-ng-legacy` feed

**Comment by hondzik** [comment]
Hi @alllexx88 
yes, it works! I was able to install ipkg and mysql 5.7.9 too. After few tests I decided to downgrade to 5.0.88, because the 5.7.9 is REALLY pretty memory-demanding and for my usage (KODI media library) I cannot justify that.
Anyway thank you for your help

**Comment by alllexx88** [comment]
@hondzik mysql 5.7.9 has proven to work fine even on mipsel routers, which have less memory and CPU than the whitelight. All it takes is an ~ 2 GB swap file, which shouldn't be an issue on a NAS. mysql 5.0.88 is *very* old, so is the cs05q1armel Optware feed you're probably using. From my experience, it takes a lot of memory, but for daily usage it's ok, since it's pages are being mostly swapped out, and remain in the swap memory, unless you're doing lots of heavy read and writes (which you normally don't, for a media library, except for while indexing large libraries -- but this process is always resource-consuming). Anyway, it's up to you to decide, but thanks for letting me know it works!

**Comment by tjmaru** [comment]
if someone faced it again, the problem is in the /usr/bin/sort util. 
My workaround is install coreutils from optware-ng and make a symlink `/opt/bin/coreutils-sort` -> `/usr/bin/sort` after that there is no problem to install any other packages.
