### ISSUE TITLE
Transmission startup script

### ISSUE THREAD

**Issue by qakcn** [Optware/Optware-ng#111]
I found Transmission startup script (`\opt\etc\inid.d\S95transmission`) forces the default download path to be `/Transmission/Complete` and cannot be changed either using the web admin or editing config file `/opt/etc/transmission-daemon/settings.json`.

**Comment by alllexx88** [comment]
@qakcn I believe this is now fixed. Now `/opt/etc/init.d/S95transmission` looks for `${REL_DLPATH}` (user-editable parameter in `/opt/etc/init.d/S95transmission`) on all mounted writable ext/fat/fuse filesystems when constructing `DIR_DL`, if not found -- creates it on the first mount of this kind. This behaviour can be overridden by setting `DIR_DL` (by editing line 15 of `/opt/etc/init.d/S95transmission`) to point to the root download dir. The actual download dirs are:
* Complete downloads: ${DIR_DL}/Complete
* Incomplete downloads: ${DIR_DL}/Incomplete
* Watch dir: ${DIR_DL}/Watch

**Comment by qakcn** [comment]
I know this, but I set them in Transmission web UI, and it stores the settings in `settings.json`, I want Transmission to get those settings from `settings.json` than set them in startup script

**Comment by alllexx88** [comment]
I don't want to change the default behaviour, since there's a guide by @TeHashX that relies on it. @TeHashX, btw, is the author of the original rc script.

However, I've made adjustments so that if *both* `DIR_DL` and `REL_DLPATH` are empty, than `settings.json` aren't overridden. Just edit `/opt/etc/init.d/S95transmission` and make them empty (this file is treated as a config file, so won't be overwritten  on package upgrade).

**Comment by qakcn** [comment]
Thanks for your help.

**Comment by TeHashX** [comment]
I didn't created the script,  found it somewhere and modified :) 
Tried to modify download path without success until I found the issue here. I don't think it's normal to modify /opt/etc/init.d/S95transmission but settings.json with transmission-daemon stopped. 
Also, can you update to v2.92?
Thanks!

**Comment by alllexx88** [comment]
@TeHashX done: 1befbc73780d36e8147fb1253441dd90d3f99d2e
