### ISSUE TITLE
Change GUI for transmission package or add alternative package

### ISSUE THREAD

**Issue by tomasiek** [Optware/Optware-ng#118]
Is it possible to change the gui for the transmission of the original with this :+1: https://github.com/ronggang/transmission-web-control
or add it as a separate package?

**Comment by alllexx88** [comment]
I don't want to replace the stock transmission web ui, and I see no way for it to be made a separate package, since it would have to replace the existing ui. However, I modified the author's install script to be used with Optware-ng (run if after installing `wget-ssl` package):

```
#!/bin/sh
rootFolder=/opt/share/transmission
webFolder=/opt/share/transmission/web
orgindex="index.original.html"
index="index.html"
tmpFolder="/opt/tmp/tr-web-control/"
packname="transmission-control-full.tar.gz"
host="https://github.com/ronggang/transmission-web-control/raw/master/release/"
donwloadurl="$host$packname"
if [ ! -d "$tmpFolder" ]; then
	mkdir -p "$tmpFolder"
fi
cd "$tmpFolder"

echo "Transmission Web Control Is Downloading..."
/opt/bin/wget --no-check-certificate "$donwloadurl"
echo "Installing..."
tar -xzf "$packname"
rm -f "$packname"

if [ ! -f "$webFolder$orgindex" -a -f "$webFolder$index" ]; then
	mv -f "$webFolder$index" "$webFolder$orgindex"
fi

cp -af web "$rootFolder"
echo "Done."

rm -rf "$tmpFolder"
```

I also made `/opt/share/transmission/web/index.html` user-editable, so that it doesn't get overwritten on package upgrade.

**Comment by tomasiek** [comment]
ok, it works. Can you add the script to the packet transmission to give a choice? This gui is much better than the original.
