### ISSUE TITLE
Request: PhantomJS

### ISSUE THREAD

**Issue by GammaC0de** [Optware/Optware-ng#123]
PhantomJS is a headless WebKit scriptable with a JavaScript API. It has fast and native support for various web standards: DOM handling, CSS selector, JSON, Canvas, and SVG.

http://phantomjs.org/
https://github.com/ariya/phantomjs

**Comment by alllexx88** [comment]
PhantomJS is a hard one to add, mainly because:

* it uses a pretty non-standard nontransparent build system, which makes it hard to cross-compile. I'm not even sure cross-compilation is possible with this system: google for "cross-compile phantomjs" yourself -- it doesn't look like anybody ever done it
* it requires QT: base and WebKit, which are currently not available on Optware-ng

**Comment by GammaC0de** [comment]
Ok, Thanks :+1: 
 :cry:
