### ISSUE TITLE
localdef not found

### ISSUE THREAD

**Issue by nsouch** [Optware/Optware-ng#131]
Hi,

glibc-locale_2.21-3_i686.ipk seems broken and always return "not found" :
Syno> /opt/bin/localedef --help
-ash: /opt/bin/localedef: not found
Syno>

Thx for your support.

**Comment by alllexx88** [comment]
Hi,

Thanks for the report: there indeed was a bug in buildroot-i686: fixed in 7981dcb466e4108f11bff16841229bce578b62da. It's being built right now (http://jenkins.nas-admin.org/view/Optware/job/Optware_Build_004_buildroot-i686/271/console), the toolchain has to be rebuilt for this. As soon as it's built and indexed, the fixed version will be online. For now, as a dirty hack, you can do this: `ln -sf ld-linux.so.2 /opt/lib/ld-linux-armhf.so.3`

**Comment by nsouch** [comment]
Thx. Indeed it works with the hack above.

**Comment by alllexx88** [comment]
You shouldn't need the hack now:

```
rm -f /opt/lib/ld-linux-armhf.so.3
ipkg update
ipkg upgrade
```

**Comment by nsouch** [comment]
Yep, that works.
