### ISSUE TITLE
rsync possibly needs rebuild.

### ISSUE THREAD

**Issue by TheMuso** [Optware/Optware-ng#147]
I'm using optware-ng i686 on a synology NAS. I use rsnapshot to do some file backups to a connected drive. My rsnapshot config points to /opt/bin/rsync, which of course is a dependency of rsnapshot. However, when attempting to run /opt/bin/rsync, I got an unable to find shared library error:

/opt/bin/rsync: error while loading shared libraries: libacl.so.1: cannot open shared object file: No such file or directory

I adjusted my config to use my NAS copy of rsync, and of course all is well. In addition, I installed libacl from optware-ng, and the above referenced binary works properly.

I was previously using optware, then entware-ng, hense my rsnapshot config referring to rsync in /opt, and it has worked up till now.

I also happen to have an optware-ng build environment set up locally as I am looking to submit a request to add a new package, so I decided to take a look at rsync. I see no references to libacl in the rsync make file, and a local build of rsync did not show any linking against libattr or libacl. So something in the build environment seems incorrect. I haven't downloaded ipk packages for other architectures to see if they are also linked against libacl.

Thanks for optware-ng.

**Comment by alllexx88** [comment]
The problem with libacl and rsync is that libacl is actually an optional dependency, and the default behaviour of the configure script is to test for its availability and enable ACL support if libacl is found and usable. What happens is that if libacl was previously staged before configuring rsync (the case with the Build machine), than it's linked against, but in your case you probably don't have it staged, so no linking with. There're two ways to fix this: either add libacl dependency, or configure with `--disable-acl-support` switch. I think the first solution is better, since ACL support in rsync can in fact be useful.

This is actually a global issue, automatically picking up additional libs, that is. This calls for writing a script/program to test for missing libraries dependencies after the entire feed is built by comparing ELF objects NEEDED entries to shared libraries provided by all the recursive dependencies. I plan to have a closer look at how they do something like this in OpenWRT, I think they use a mix of Makefiles and bash scripts for this. I should see how easy it is to adapt their work to Optware-ng, don't want to reinvent the bycicle :smile:

**Comment by TheMuso** [comment]
Yeah I had other things to do, so since I saw no reference to anything all in the package makefile, I thought it was something that was picked up somewhere.

**Comment by alllexx88** [comment]
It's a bit early to close this, since the fix is obvious, but not yet applied (like I mentioned in your PR already, we should wait till the DNS-related issue is fixed first), so re-opening to not forget about it :wink:
