### ISSUE TITLE
Samba 3

### ISSUE THREAD

**Issue by Authxx** [Optware/Optware-ng#153]
Hello! i have a problem with samba after install
auth@RT-N66U:/tmp/mnt/sda1/optware-ng/etc/init.d# /opt/etc/init.d/S08samba restart 
Starting nmbd: 
Starting smbd: 
/tmp/mnt/sda1/optware-ng/sbin/smbd: can't load library 'libavahi-common.so.3'

**Comment by alllexx88** [comment]
That's a dependency bug: `libcups` should depend on `avahi`. I've recently written a script that helps detecting such missing library dependencies, and am currently in process of fixing them, but it'll take a while, since there're lots of them, and I'm currently away from PC for a while. I'll fix it eventually, for now simply install `avahi` package

**Comment by Authxx** [comment]
thank you for quick response
