### ISSUE TITLE
Fail to to install ruby gem rmagick 

### ISSUE THREAD

**Issue by Johnsik** [Optware/Optware-ng#168]
`ipkg install imagemagick`
`Package imagemagick (6.9.3.5-1) installed in /opt/ is up to date.`

`gem install rmagick`

```
Building native extensions.  This could take a while...
ERROR:  Error installing rmagick:
        ERROR: Failed to build gem native extension.

    current directory: /share/CACHEDEV2_DATA/.qpkg/Optware-ng/lib/ruby/gems/2.3.0/gems/rmagick-2.16.0/ext/RMagick
/opt/bin/ruby -r ./siteconf20161018-22005-fmtsb0.rb extconf.rb
checking for /opt/bin/gcc... yes
checking for Magick-config... yes

Warning: Found a partial ImageMagick installation. Your operating system likely has some built-in ImageMagick libraries but not all of ImageMagick. This will most likely cause problems at both compile and runtime.
Found partial installation at: /opt
checking for outdated ImageMagick version (<= 6.4.9)... no
checking for presence of MagickWand API (ImageMagick version >= 6.9.0)... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/bin/$(RUBY_BASE_NAME)
extconf.rb:104:in ``': No such file or directory - MagickWand-config (Errno::ENOENT)
        from extconf.rb:104:in `configure_compile_options'
        from extconf.rb:16:in `initialize'
        from extconf.rb:548:in `new'
        from extconf.rb:548:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/lib/ruby/gems/2.3.0/extensions/x86-linux/2.3.0/rmagick-2.16.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /opt/lib/ruby/gems/2.3.0/gems/rmagick-2.16.0 for inspection.
Results logged to /opt/lib/ruby/gems/2.3.0/extensions/x86-linux/2.3.0/rmagick-2.16.0/gem_make.out
```

**Comment by walataza** [comment]
Hello @johnsik. Did you get this fixed?

**Comment by Johnsik** [comment]
Hello @walataza! Not yet.

**Comment by walataza** [comment]
Same here, I’m looking for a fix, but I have heard that using an earlier version prior to 7.0 works. I am downloading the file and would try it. I’ll let you know if that fixes it

cheers

**Comment by walataza** [comment]
I finally got it fixed... You actually need to use an earlier version. I downloaded the 6.9.9 version. you can search via sourceforge incase you have an x86 pc
https://netcologne.dl.sourceforge.net/project/imagemagick/im6-exes/ImageMagick-6.9.9-4-Q16-x64-dll.exe

1. Download the file and install(make sure there is no space between, so better to install in C: drive directly than in program files because of the space)
2. Open cmd, enter into the path C:\ImageMagick-6.9.9-Q16 and then set CPATH=C:\ImageMagick-6.9.9-Q16\include
3. Do the same above but this time to set library path - set LIBRARY_PATH=C:\ImageMagick-6.9.9-Q16\lib
4. Now go into your app directory e.g  C:\DEV\App\AMP>gem install rmagick -- '--with-opt-dir="C:\ImageMagick-6.9.9-Q16"'

Below was what i got
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions with: '--with-opt-dir="C:\ImageMagick-6.9.9-Q16"'
This could take a while...
Successfully installed rmagick-2.16.0
Parsing documentation for rmagick-2.16.0
Installing ri documentation for rmagick-2.16.0
Done installing documentation for rmagick after 2 seconds
1 gem installed

Then do gem list to see that it is there.

**Comment by alllexx88** [comment]
I've got it working properly now:

1. Install packages: `ipkg update; ipkg install gcc pkgconfig ruby imagemagick`
2. Build `rmagick`:

```
root@DiskStation:~# gem install rmagick
Fetching: rmagick-2.16.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed rmagick-2.16.0
Parsing documentation for rmagick-2.16.0
Installing ri documentation for rmagick-2.16.0
Done installing documentation for rmagick after 55 seconds
1 gem installed
```

**Comment by walataza** [comment]
Thanks again...
Funny thing is I'm on windows .
It worked perfectly and just a few days ago the error came back.. in trying to see how to fix again.
If you have options for windows , please send it in.. thank you

**Comment by alllexx88** [comment]
> Funny thing is I'm on windows .

Optware-ng doesn't run on Windows... Probably, you were/are just having seemingly similar issue. On Optware-ng build was failing due to missing `MagickWand-config` script, and some missing `imagemagick` package dependency libs. I've fixed that, and now it's working fine, but Windows issue is unrelated here, not sure I can help you, sorry

P.S. A good place to start debugging build error is `mkmf.log`, it's location is printed when build fails, likes this:

```
To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/lib/ruby/gems/2.3.0/extensions/x86-linux/2.3.0/rmagick-2.16.0/mkmf.log
```

**Comment by walataza** [comment]
OK then, thanks alot and enjoy the rest of your week

cheers

**Comment by Johnsik** [comment]
Thank you @alllexx88 !
All works!
