### ISSUE TITLE
Python uses wrong path for libarys

### ISSUE THREAD

**Issue by satfreak** [Optware/Optware-ng#194]
I playing around with optware-ng, to look if its suitable to use on qnap qts 4.3 and higher.
A thing which was a surprise to me, was when i installed pip.
In the /opt directory, there came a directory local, and with in ther a bin and lib directory.
According to linux rules, this should be /opt/usr/local.
And if i compare it to other optware packets, they al put in in /opt/lib and /opt/bin

So could this please be fixed ?

**Comment by alllexx88** [comment]
> According to linux rules, this should be /opt/usr/local.

Which rules do you mean exactly? `/opt` is the default Optware prefix, just like `/usr` is standard for most linux distributions. And the same way `pip` installs to `/usr/local` on desktop linux, Optware `pip` installs to `/opt/local`. Why would you want it to be `/opt/usr/local` instead?

**Comment by satfreak** [comment]
Because if you look in the structuur of anything in linux, the normaal path use is always /usr/local/.
And when you would look in the old first optware, with python it was /opt/usr/local/.
So one has in mind when adding this to the path, it should look like /opt/local/bin and /opt/usr/local/sbin/

**Comment by alllexx88** [comment]
Optware isn't a linux distro, it in a sense runs on top of an existing firmware, Optware and fw exist side-by-side. As such, it uses a different paths convention: while `/usr` is the usual system-wide user space prefix in most linux distros, Optware uses `/opt`. e.g., libs go to `/opt/lib`, executables -- to `/opt/bin` or `/opt/sbin`. No Optware  packages install to other locations. Optware `pip` installs to `/opt/local`, just like normal linux distros `pip` installs to `/usr/local` (as opposed to `/usr`). This "old first optware" you're referring to must have been a bug, since there was no `pip` package back then, and `python` was supposed to go to `/opt` prefix -- not `/opt/usr/local`

**Comment by satfreak** [comment]
Oke well , thanks for explaining it.
