### ISSUE TITLE
 Package request: usb-modeswitch

### ISSUE THREAD

**Issue by me11ved** [Optware/Optware-ng#234]
Hi Alex.
Please configure the package: usb-modeswitch
Thank you!

**Comment by alllexx88** [comment]
Hi. I've been looking into it for a while. Looks like adding the original [usb_modeswitch](http://www.draisberghof.de/usb_modeswitch) is not an option, since it relies on udev heavily to do the switching. The other option is to add OpenWRT's [usbmode](http://git.openwrt.org/?p=project/usbmode.git), which can run as a daemon and doesn't need udev. The latter needs OpenWRT's [libubox](http://git.openwrt.org/?p=project/libubox.git), so I'll need to do this first. Doing so is on my To-Do list, so please stay tuned 😄

**Comment by alllexx88** [comment]
Added. Usage:

```
Usage: /opt/sbin/usbmode <command> <options>
Commands:
        -l              List matching devices
        -s              Modeswitch matching devices

Options:
        -v              Verbose output
        -c <file>       Set configuration file to <file> (default: /opt/etc/usb-mode.json)
```

If your device firmware supports custom hotplug scripts (e.g., TomatoUSB does), you can add `/opt/sbin/usbmode -s` hotplug command to automatically switch supported devices. If not, you'll have to manually call. In theory, at least, since I don't have a supported device here that can be switched, so feedback is appreciated 😄

**Comment by me11ved** [comment]
Thanks, Alex. 
The problem is found in the firmware of merlin.
After updating the program, the modem does not see it. I had to roll back the firmware.
