### ISSUE TITLE
[Request] ChironFS

### ISSUE THREAD

**Issue by dduck669** [Optware/Optware-ng#272]
Can you please build package for ChironFS (source https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/chironfs/chironfs-1.1.1.tar.gz)?
Homepages are: https://github.com/tweksteen/chironfs and http://www.furquim.org/chironfs/index.en.html)

Please let me know.
Thank you.

Regards

**Comment by alllexx88** [comment]
I'm somehow hesitant to add `chironfs` package, since

1. There haven't been any updates by the original developer for ~9,5 years (last version on http://www.furquim.org/chironfs/index.en.html released on Jun 21, 2008)
2. I don't see a `chironfs` package on most major Linux distributions (checked Debian/Ubuntu, Fedora Red Hat, Arch Linux), which can mean that it is indeed outdated and not considered secure
3. The github fork you mentioned doesn't look like it's being maintained anymore as well: the development stopped after few commits back in summer 2015. Also, no Issues there, or any other signs of it being used

**Comment by dduck669** [comment]
I understand... So, as alternative in possible to add the package csync2?

**Comment by alllexx88** [comment]
@dduck669 csync2 looks good per cursory inspection. I will look into adding it, however, please create a separate issue for csync2.
