### ISSUE TITLE
Entware-ng_0.97.qpkg - not possible set shared folder permissions on newly created shared folders

### ISSUE THREAD

**Issue by pezacz** [Optware/Optware-ng#306]
**Symptoms:**
impossible to set permissions on any shared folder created after Entware was installed

### How to reproduce:
1, Install Entware-ng_0.97.qpkg using Apps|Settings|Install manually
2, reboot (essential) - before reboot, but after installation everything still works fine
3, create shared folder
4, try to set permissions

**System details:**
Model 439
Firmware 4.2.6  2018/10/26
32-bit
sha1 c8849a417c147f0f6fad981fb090e39eb3a832d9 *Entware-ng_0.97.qpkg
md5 c8849a417c147f0f6fad981fb090e39eb3a832d9 *Entware-ng_0.97.qpkg

**Further info:**
-NAS was re-initialized multiple times to confirm that Entware is s really responsible for this behavior
-deinstalling Entware and reboot doesn't make things working again - NAS must be re-initialized
-shared folders created before entware was installed are still available for permission change
-deleting and re-creating shared folder with the same name also can't set permissions
-/share/<foldername> link is NOT created
-the shared folder itself /share/HDA_DATA/<foldername> is created
-the problem did not start with newest firmware

That unfortunately makes Entware not usable at all for me :(

After making appointment, I can provide TeamViewer access if it helps you to diagnose the issue.
![bug_step01](https://user-images.githubusercontent.com/23435146/48282857-2775f980-e45b-11e8-8742-49c062da49d1.png)
![bug_step02](https://user-images.githubusercontent.com/23435146/48282858-280e9000-e45b-11e8-8517-a550bc1e4f26.png)
![bug_step03](https://user-images.githubusercontent.com/23435146/48282859-280e9000-e45b-11e8-9cda-06be2c5de8db.png)

**Comment by alllexx88** [comment]
I'm not sure where you should report this: to Entware-ng issue tracker, or to whoever packaged Entware-ng_0.97.qpkg, but Optware-ng has nothing to do with this issue.

**Comment by pezacz** [comment]
I've tried 
md5 a7877bebc06f11e05d0fb026918223ef *Optware-NG_2.05.qpkg
with the same result on freshly re-initialized TS-439.
There is one minor difference - missing icon:
![bug04](https://user-images.githubusercontent.com/23435146/48291194-d58e9d00-e475-11e8-9d13-ecd38c4e5943.png)

Would you be willing to investigate ?

**Comment by alllexx88** [comment]
Both Entware and Optware reside only under `/opt`, and unless your firmware uses `/opt` too (which it shouldn't do, since `/opt` dir is for "the installation of add-on application software packages", see [Filesystem Hierarchy Standard](http://www.pathname.com/fhs/pub/fhs-2.3.html)), it shouldn't cause problems like what you describe. Yes, you can install and run some packages, which could occupy a resource, e.g., port, and thus make it unavailable for firmware components, but that doesn't seem to be the case, since the problem occurs right after you install the qpkg's.

That all being said, my best bet is that the issue lies somewhere in the qpkg's, and you should approach the author of these packages. Also, I can't really do much to investigate this issue, since I have no TS-439, nor any other QNAP boxes at all.

**Comment by pezacz** [comment]
to put some closure to it in case someone else ends on the same route.

After endless reinicializations and factory resets and trying to identify what exactly is the problem I've re-installed the firmware after downloading from QNAP website.
If I'm not mistaken, this was already second time, but first time was couple of days ago at the beginning of this story.
At the end - I'm on 6c81cc37cbadd85adfb2751dc06a238f *Entware-ng_0.97.qpkg and everything works as it should.
