### ISSUE TITLE
UniversalMediaServer

### ISSUE THREAD

**Issue by steom** [Optware/Optware-ng#40]
package request
https://github.com/UniversalMediaServer/UniversalMediaServer/

**Comment by alllexx88** [comment]
I can start the X11 screen, using OpenJDK7, and then access on port 9001 the folders I've indexed, but I didn't manage to get transcoding to work. Only "no transcoding" mode works, and for some odd reason it's sometimes greyed out, sometimes not. Since I can't make it work properly, I won't add it to the repos, sorry
