### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by djxwolf** [Optware/Optware-ng#55]
I installed optware-ng successfully. 
Now I installed gcc and tried to compile a simple hello binary.
hello.c :

#include <stdio.h>
int main()
{
        printf("Hello World!\n");
	return 0;
}

compiled successfully with command: gcc -o hello hello.c
I tried to execute it and failed with the following messages:

hello: can't load library 'libc.so.1'

I think it didn't find libc.so.1 in /lib. In fact only libc.so.0 exists in /lib.
so I set LD_LIBRARY_PATH=/lib:/usr/lib:/opt/lib:/opt/usr/lib and execute hello again,
now it failed with the following messages:

hello: '/opt/lib/libc.so.1' library contains unsupported TLS
hello: can't load library 'libc.so.1'

How can i compiled it to run successfully?
i tried to compiled it with -static option and run it fine.
what's the problem with the dynamic version?

**Comment by alllexx88** [comment]
`gcc`, just like other Optware-ng packages, doesn't use firmware's libc. You need to pass additional link flags to link with Optware-ng's uclibc-ng and other libs:
```
LDFLAGS='-Wl,--dynamic-linker=/opt/lib/ld-uClibc.so.1 -Wl,-rpath=/opt/lib -L/opt/lib' \
CPPFLAGS='-I/opt/include' \
./configure \
--prefix=/opt/local \
...
```
You may need to add more `-Wl,-rpath=/opt/lib/<..> -L/opt/lib/<..>` if you use libraries that reside in `/opt/lib/...` subfolders. The same goes for CPPFLAGS. Also, not all packages come with headers/have dev versions, so you may need to download appropriate headers yourself.

Make sure not to mix fimrware's libraries with Optware-ng ones: they're not compatible. TLS (thread local storage) is enabled in Optware-ng uclibc-ng, and this kind of error happens if firmware's default dynamic linker is used, which is build without TLS.

Unfortunately, you can't build firmware dynamic binaries with Optware-ng toolchain (at least, for uclibc-ng targets), but you can, for instance, copy all Optware-ng libs you need to a separate directory, and pass ldfalgs to use those instead of ones that reside in `/opt/lib/..` --- this way your binaries will remain functional, even if your Optware-ng setup breaks.

Optware-ng native compilation isn't as transparent as native compilation usually is, so you may encounter more issues, e.g., when using `pkgconfig`

In your simple example, just add '-Wl,--dynamic-linker=/opt/lib/ld-uClibc.so.1 -Wl,-rpath=/opt/lib -L/opt/lib' flags, and it should suffice.

**Comment by djxwolf** [comment]
Thanks for your reply. Very detail.
That solved my problem.
