### ISSUE TITLE
binaries linked against /lib/ld-linux.so.2 instead of /opt/lib/ld-linux.so.2

### ISSUE THREAD

**Issue by gits68** [Optware/Optware-ng#73]
arch i686

**update**

yet another check against RPATH using objdump...

$ cd /opt/bin
$ for i in $(file * | awk -F: '/dynamically linked/{print $1}'); do objdump -x $i | grep -q RPATH || echo $i; done
catdoc
catppt
fdupes
flex
iconv
iostat
mpstat
pidstat
sadf
sar
xls2csv
xxd

$ cd /opt/sbin
for i in $(file * | awk -F: '/dynamically linked/{print $1}'); do objdump -x $i | grep -q RPATH || echo $i; done
tinyproxy

yet another solution to check the right linker

$ file * | awk -F: '/dynamically linked/&&!/opt/{print $1}'
same as
$ ldd * | awk '/:$/{x=$1;next}/ld-linux.so.2/&&!/opt/{print x}'

**end of update**

$ cd /opt/bin
$ ldd * | awk '/:$/{x=$1;next}/ld-linux.so.2/&&!/opt/{print x}' | sed 's!^!/!;s/:/$/' > /opt/tmp/ko2
$ cd /opt/lib/ipkg/info
$ grep -f /opt/tmp/ko2 *.list
catdoc.list:/opt/bin/xls2csv
catdoc.list:/opt/bin/catdoc
catdoc.list:/opt/bin/catppt
fdupes.list:/opt/bin/fdupes
fdupes.list:/opt/bin/fdupes
flex.list:/opt/bin/flex
gconv-modules.list:/opt/bin/iconv
sqlite.list:/opt/bin/sqlite3
sendmail.list:/opt/bin/vacation
sysstat.list:/opt/bin/mpstat
sysstat.list:/opt/bin/mpstat
sysstat.list:/opt/bin/mpstat
sysstat.list:/opt/bin/mpstat
sysstat.list:/opt/bin/iostat
sysstat.list:/opt/bin/sar
sysstat.list:/opt/bin/sadf
sysstat.list:/opt/bin/pidstat
vim.list:/opt/bin/xxd

$ cd /opt/sbin
$ ldd * | awk '/:$/{x=$1;next}/ld-linux.so.2/&&!/opt/{print x}' | sed 's!^!/!;s/:/$/' > /opt/tmp/ko4
$ cd /opt/lib/ipkg/info
$ grep -f /opt/tmp/ko4 *.list
sendmail.list:/opt/sbin/mailstats
sendmail.list:/opt/sbin/smrsh
sendmail.list:/opt/sbin/editmap
sendmail.list:/opt/sbin/praliases
sendmail.list:/opt/sbin/makemap
tinyproxy.list:/opt/sbin/tinyproxy

**Comment by alllexx88** [comment]
That's a very helpful report, thank you!
I believe the issues are fixed with following commits:
bcc0a1a4c834885a926409368b7b92d5a908ec22
04968e692998d31b67c0d6e6f1f0de2f1a84f8dd
0e0f40d2b96fd14eadf6540d5e442df55df357d6
8d3ccf0fec355d9f5ab694047db677e39bab68c0
6d5dbac2c2068fab30cf9696033982eafaababb1
9aad4bcfb9f186bfa8f7b06730914b50669a5a73
57c9c9d344f9ada425908166778e185be4d346d9
48c0d6e1c0feef1b7966114517a67f19aaf122d8
615671aed1c8f0608f586a2070cbdfe7798ed9ed

Fixed packages are now online

**Comment by gits68** [comment]
thanks,well done :)
