### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by clsalva** [Optware/Optware-ng#78]
Hello, trying to compile any program source, i get the same error

> <2012.1-2.3.1] # ./configure --prefix=/opt --enable-amule-daemon
checking for a BSD-compatible install... /opt/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /opt/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking if this is a FreeBSD 4 or earlier system... no
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/opt/share/aMule-AdunanzA-2012.1-2.3.1':
configure: error: cannot run C++ compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
[/opt/share/aMule-AdunanzA-2012.1-2.3.1] #

> 

The following is an extract of config.log where the error occurs.

> configure:3890: checking for C++ compiler default output file name
configure:3892: result: a.out
configure:3898: checking for suffix of executables
configure:3905: g++ -o conftest    conftest.cpp  >&5
configure:3909: $? = 0
configure:3931: result:
configure:3953: checking whether we are cross compiling
configure:3961: g++ -o conftest    conftest.cpp  >&5
configure:3965: $? = 0
configure:3972: ./conftest
./configure: line 3974: ./conftest: No such file or directory
configure:3976: $? = 127
configure:3983: error: in `/opt/share/aMule-AdunanzA-2012.1-2.3.1':
configure:3985: error: cannot run C++ compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

> 

Might it be related to GCC version/configuration or there's something i'm missing?

thanks in advance
Claudio

**Comment by alllexx88** [comment]
Hi Claudio,
You need to pass additional compilation (if using headers in `/opt/include`) and linking flags if you want to compile using Optware-ng gcc, e.g., for buildroot-armeabihf you're using:
LDFLAGS="-Wl,--dynamic-linker=/opt/lib/ld-linux-armhf.so.3 -L/opt/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link,/opt/lib" CPPFLAGS="-I/opt/include" ./configure --prefix=/opt --enable-amule-daemon

**Comment by clsalva** [comment]
Hi alllexx, thank. That worked out. But i still have a problem when compiling.
Here an example:

> checking for pkg-config... /opt/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for HARFBUZZ... yes
checking for FONTCONFIG... no
checking for CoreText availability... no
checking for CAIRO... no
configure: error: *** Could not enable any backends.
*** Must have at least one backend to build Pango.
[/share/CACHEDEV1_DATA/Public/pango] # ipkg install fontconfig
Package fontconfig (2.8.0-0) installed in /opt/ is up to date.
Nothing to be done
Successfully terminated.
[/share/CACHEDEV1_DATA/Public/pango] # ipkg install freetype
Package freetype (2.5.5-1) installed in /opt/ is up to date.
Nothing to be done
Successfully terminated.
[/share/CACHEDEV1_DATA/Public/pango] # ipkg install harfbuzz
Package harfbuzz (0.9.38-1) installed in /opt/ is up to date.
Nothing to be done
Successfully terminated.
[/share/CACHEDEV1_DATA/Public/pango] # ipkg install cairo
Package cairo (1.14.2-1) installed in /opt/ is up to date.
Nothing to be done
Successfully terminated.
[/share/CACHEDEV1_DATA/Public/pango] #

I've Pango installed thru Optware, but it's not recognized.
I've Cairo installed...not recognized...
And that happens with many of the packages installed (e.g. GTK+, gtk-doc). They might be installed, but not seens when compiling programs not in the packages repository.
Is there something i'm missing in configuring my NAS/Optware?

thank you 
Claudio

**Comment by alllexx88** [comment]
Hi,

I remember I saw something similar, but I can't find where, neither remember the exact solution. Sorry, I don't provide support for native development: the tools for this are shipped 'as-is'. That is, I'm glad to help if it takes simply writing the answer I know, but I won't be looking into issues you encounter specifically, since this lies beyond the purpose of the project. You're on your own here: look at config.log, google, study the build system deeper if you must. And I wish you good luck at that.

Regards,
Alex

**Comment by mskyaxl** [comment]
I have the same issue...I'm no linux expert, maybe I'm asking something stupid... but what is the purpose of including these packages into the bootstrap in the first place if you're not able to use them -> to compile with them on the target?

**Comment by alllexx88** [comment]
@mskyaxl you *are* able to compile using these packages, and beyond certain Optware-ng-specific flags most issues you face aren't Optware-ng-specific, and usually come from a non-standard prefix. Like poorly designed sourcecode that works with standard prefix, but fails to pass custom flags properly. Compilation is *always* complicated, and if you're brave enough to venture building complicated projects, get ready to face the inevitable difficulties: don't expect me, or someones else, to kindly guide you throughout the entire process. It's always a steep learning curve, and if you're not ready to accept this, it's probably just not your thing.

**Comment by mskyaxl** [comment]
@alllexx88 thanks for your "kind" explanation. It's not about accepting things but about learning things. I don't expect to be guided throughout the entire process but I also think that asking questions can help me understand things. I apologize if I offended you but the question was not an attack to a person but more a curiosity, just to learn why you are doing it. My background is in non linux embedded systems, also sw development, and just because I'm asking here it means that I'm in that "steep learning curve".

**Comment by alllexx88** [comment]
@mskyaxl The original issue reported by @clsalva was resolved by adding appropriate compilation and linking flags. The second issue was related to the mechanism used in pango sourcecode to locate the cairo backend. It probably takes passing additional configure flag or setting environment variable to fix this, but I don't know the answer, and I think I gave a clear explanation to why I would not look into the sourcecode myself -- this is not what this project is about. All those graphics-related packages are a pain to build in non-standard environment. Then you hijack this closed issue saying you have "the same issue" -- not even mentioning which exactly, and unfoundedly claim that compilation packages are not usable. It's plain rude -- whether you meant it or not. You don't create bug reports in, say, python bug tracker, saying that it doesn't work just because you failed to write code that would do what you want. Since such discussions aren't welcomed here, I'm locking this conversation.
