### ISSUE TITLE
Squid3: can't load library 'libltdl.so.7'

### ISSUE THREAD

**Issue by WaLLy3K** [Optware/Optware-ng#88]
Unable to install Squid3 due to missing dependency. Using squid (2.7.9-1) in the meantime works without issues.

```
root@Ichor:/# ipkg install squid3
Installing squid3 (3.1.8-1) to /opt/...
Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng/squid3_3.1.8-1_arm.ipk
Configuring squid3
create default cache and logs dir
/opt/sbin/squid: can't load library 'libltdl.so.7'

You should review the configuration file /opt/etc/squid/squid.conf,
make any necessary change, and complete the install by running - 
/opt/etc/init.d/S80squid start

Successfully terminated.
```

No rush when it comes to fixing this, since 2.7 works fine! Though having them compiled with LAX_HTTP=on would be handy to violate some HTTP headers for when iOS updates roll around :)

**Comment by alllexx88** [comment]
Looks like squid3 is missing libtool dependency. I'll fix it after I resolve pkg-config related compilation issues (rebuilding a feed from scratch atm to achieve this). For now, you can install it manually: `ipkg install libtool`. Also, I see squid3 is due to be updated, openwrt squid package looks nice, I'll use it to bump squid3 to 3.5.12. Might also compile it with --enable-http-violations (LAX_HTTP=on in FreeBSD ports). btw, current squid3 package probably won't work for bigendian, since it's compiled with ac_cv_c_bigendian=no, so I suspect PowerPC variant doesn't work. This is due to be fixed as well.

**Comment by WaLLy3K** [comment]
Installing libtool definitely resolves the issue. Look forward to seeing an updated version, whenever you're able to get around to it!

**Comment by alllexx88** [comment]
@WaLLy3K it's available in the feeds already: version 3.5.15 :-)

**Comment by WaLLy3K** [comment]
Ah, nice, thanks!

After attempting to perform a clean upgrade (uninstall & remove all folders first), I came across this error:
> FATAL: Ipc::Mem::Segment::create failed to shm_open(/squid-cf__metadata.shm): (13) Permission denied

However, it was resolved by using the command [chmod 777 /dev/shm](https://github.com/Entware/entware/issues/143). (For anyone that comes across this later).

**Comment by alllexx88** [comment]
Glad it works, closing the issue
