### ISSUE TITLE
Mipsel repo issues

### ISSUE THREAD

**Issue by Amp3rwater** [Optware/Optware-ng#93]
Obsolete - fixed myself.

**Comment by alllexx88** [comment]
@Amp3rwater Hi,

Just while I was writing the answer, you removed the question. I'll answer though, since I think this can still be useful to you or someone else. I hope you don't mind me citing the removed question.

> First of all thank you for your hard work. Updated optware is what I was looking for.
> Not sure what kind of info do you need to fix problems but will try to describe what I found during first installation of it.
> 
> Installed on: Tomato Firmware 1.28.0000 MIPSR2-132 K26 USB Mega-VPN
> Linux E4200 2.6.22.19 #19 Fri Oct 9 19:50:08 CEST 2015 mips GNU/Linux
> 
> PATH=/sbin:/bin:/usr/sbin:/usr/bin:/opt/sbin:/opt/bin
> LD_LIBRARY_PATH=/opt/lib:/opt/usr/lib:/lib:/usr/lib:/usr/local/lib
> Above added into: /opt/etc/profile
> 
> Basic Installation (bootstrap.sh) is fine. Would be nice to implement updating LD_LIBRARY_PATH automatically as it is the main issue with running installed packages. Uclibc-opt does not contain ldconfig - my old optware package provided such binary.
> 
> The most important package for me was hiawatha and it works fine with some small modification such as changing rights to /dev/null.
> 
> Next one was mlocate package. Its postinst script gives errors due to chgrp. Chgrp is missing, even on repo list - should be replaced to chown or added to repo. I fix it myself with chown.
> 
> I also tried to install nano and hping for test and below you find an output:
> 
> root@E4200:/tmp/home/root# locate libstdc
> /opt/lib/libstdc++.so
> /opt/lib/libstdc++.so.6
> /opt/lib/libstdc++.so.6.0.21
> /opt/lib/ipkg/info/libstdc++.control
> /opt/lib/ipkg/info/libstdc++.list
> 
> root@E4200:/opt/lib# nano
> nano: can't load library 'libstdc++.so.6'
> 
> Installing hping (20051105-4) to /opt/...
> Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-mipsel-ng/hping_20051105-4_mipsel.ipk
> Installing libpcap (1.3.0-2) to /opt/...
> Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-mipsel-ng/libpcap_1.3.0-2_mipsel.ipk
> Installing libusb1 (1.0.19-1) to /opt/...
> Downloading http://ipkg.nslu2-linux.org/optware-ng/buildroot-mipsel-ng/libusb1_1.0.19-1_mipsel.ipk
> Configuring hping
> Configuring libpcap
> Successfully terminated.
> Collected errors:
> Package libusb1 md5sum mismatch. Either the ipkg or the package index are corrupt. Try 'ipkg update'.
> root@E4200:/opt/lib# hping
> /opt/sbin/hping3: can't load library 'libusb-1.0.so.0'
> 
> As you can see to many issues at the very beggining. Do not get me wrong - I do not complain. I count on you and believe you can fix this. If my firmware is not right one for optware-ng installation or I am doing something wrong, please correct me.
> Thank you once again for optware development.

First of all, Optware-ng doesn't need `LD_LIBRARY_PATH`. Furthermore, setting it will either break it, or break firmware apps. Please remove `LD_LIBRARY_PATH=/opt/lib:/opt/usr/lib:/lib:/usr/lib:/usr/local/lib` line from `/opt/etc/profile`, or, even better, change it to `export LD_LIBRARY_PATH=''`. `ldconfig` binary is not needed, since uClibc-ng used in Optware-ng (`uclibc-opt` package) properly supports RPATH, and Optware-ng binaries are compiled to use the Optware-ng loader, thus eliminating the use of firmware uclibc (or any other libc, like musl) at all, as well as any other firmware libraries in general. This is what makes it firmware-independent. As long as kernel is at least 2.6.22.19, mipsel firmware should do fine for `buildroot-mipsel-ng` feed.

Next, `chgrp` issue. Optware-ng assumes that firmware has a minimal set of linux commands available. However, most of them can indeed be compensated for by packages in the feeds. For `/opt/bin/chgrp`, you can install `busybox` package, or, for a more classic variant of `chgrp` -- `coreutils`. I know it can be quite difficult to find binaries you need, a way to do this is to grep through http://ipkg.nslu2-linux.org/optware-ng/buildroot-mipsel-ng/Packages.filelist e.g.:

```
root@unknown:/tmp/home/root# wget -qO- http://ipkg.nslu2-linux.org/optware-ng/buildroot-mipsel-ng/Packages.filelist|grep chgrp
chgrp.1 coreutils:mipsel:./opt/man/man1/chgrp.1
chgrp.1p.gz man-pages:mipsel:./opt/man/man1p/chgrp.1p.gz
coreutils-chgrp coreutils:mipsel:./opt/bin/coreutils-chgrp
```

This didn't show busybox, since `/opt/bin/chgrp` is installed by `/opt/bin/update-alternatives` as a symlink to `/opt/bin/busybox`, so there's no binary called `chgrp` in busybox actually.

As for `libusb1`, I assume `ipkg update` should fix such issues.

Hope this will be useful, to you, or to someone else.

Regards,
Alex

**Comment by Amp3rwater** [comment]
Hi,

Excellent answer. Thanks a lot. I have been searching for chgrp but did not find it. Still learning linux. :)  Meanwhile, I removed LD_LIBRARY_PATH and looks like now all works fine, even nano.
I called nano instead of /opt/bin/nano that's why had an error I guess. I closed issue to not mess around. I believe you have more important issues to fix. Anyway, I am really glad there is a good contact with you.
Coreutils package is the one I needed.

Regards
Jarek
